// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvxhPEBeRktA-NHPd7NQYQCKLY0yVdOM',
    appId: '1:205220792001:web:26349f1c47ad4237b03640',
    messagingSenderId: '205220792001',
    projectId: 'chatapplication-65f46',
    authDomain: 'chatapplication-65f46.firebaseapp.com',
    storageBucket: 'chatapplication-65f46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rX6txD0_mKxeaPRwGCM3YRQdm4MyUgs',
    appId: '1:205220792001:android:473a37f43faf414cb03640',
    messagingSenderId: '205220792001',
    projectId: 'chatapplication-65f46',
    storageBucket: 'chatapplication-65f46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaEnL832-pdmTBQGpu23IjZiNIdZataFQ',
    appId: '1:205220792001:ios:11447b9df4c5e444b03640',
    messagingSenderId: '205220792001',
    projectId: 'chatapplication-65f46',
    storageBucket: 'chatapplication-65f46.appspot.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaEnL832-pdmTBQGpu23IjZiNIdZataFQ',
    appId: '1:205220792001:ios:11447b9df4c5e444b03640',
    messagingSenderId: '205220792001',
    projectId: 'chatapplication-65f46',
    storageBucket: 'chatapplication-65f46.appspot.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUvxhPEBeRktA-NHPd7NQYQCKLY0yVdOM',
    appId: '1:205220792001:web:5f47948d1f2bf6dcb03640',
    messagingSenderId: '205220792001',
    projectId: 'chatapplication-65f46',
    authDomain: 'chatapplication-65f46.firebaseapp.com',
    storageBucket: 'chatapplication-65f46.appspot.com',
  );
}
